#通用配置文件
#springboot整合mybatis框架
#加载Mybatis配置文件
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mapper/config/sqlMapConfig.xml
#数据源
spring:
  datasource:
    url: jdbc:mysql://192.168.150.129:3306/gzfwpt
    driver-class-name: com.mysql.jdbc.Driver
    username: lixiang
    password: Mysql520_
  mvc:
    view:
      #页面默认前缀目录
      prefix: /WEB-INF/pages/jsp/
      #响应页面默认后缀
      suffix: .jsp
  resources:
    static-locations: /WEB-INF/resource/
  redis:
    host: 192.168.10.219
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.10.55
    port: 5672
    username: test
    password: test123
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    
logging:
  level:
    com:
      turbur:
        mapper: DEBUG

        
demo: ahhahahah